---------------
-- Neo4j
---------------
:HELP
:SEVER DISCONNECT
:SERVER CONNECT 
:PLAY START
:SERVER STATUS
:SYSINFO
:QUERIES




principais palabras da linguagem CYPHER

CREATE = CRIAR - NODE E RELACIONAMENTO
MATCH = SELECT
RETURN = MOSTRA O VALOR CRIADO (RETORNA)
WHERE = SELECAO
SET = UPDATE
REMOVE = DELETE
MERGE = CRIAR UM OBJETO DERIVADO

LABEL - ANALOGA AO NOME DE UMA TABELA 

PROPRIEDADE - ANALOGA AO NOME DE COLUNAS