--CRIANDO CONTINENTES

CREATE (:CONTINENTE {NOME: 'AMERICA DO SUL'})
CREATE (:CONTINENTE {NOME: 'AMERICA DO NORTE'})
CREATE (:CONTINENTE {NOME: 'EUROPA'})
CREATE (:CONTINENTE {NOME: 'AFRICA'})
CREATE (:CONTINENTE {NOME: 'ASIA'})


----------------------------------------------