----------------------------------------------
--CRIANDO RELACIONAMENTO 

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
CREATE (P)-[R : PERTENCE]->(C)
RETURN P,C,R

--RELACIONAMENTO BIDIMENCIONAL

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
CREATE (P)<-[R : CONTEM]-(C)
RETURN P,C,R]

--TRAZENDO O RELACIONAMENTO 

MATCH (P: SELECAO), (C: CONTINENTE)
WHERE P.NOME = 'COLOMBIA'AND C.NOME = 'AMERICA DO SUL'
RETURN P,C

--OUTRA FORMA 

MATCH (P: SELECAO)-[R:PERTENCE]->(C: CONTINENTE)
WHERE P.NOME = 'COLOMBIA'AND C.NOME = 'AMERICA DO SUL'
RETURN P,C,R

--DELETANDO RELACIONAMENTO
MATCH (P:SELECAO)-[R:PERTENCE]->(C:CONTINENTE)
WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
DELETE R
RETURN P,C