--MERGE (nÃO DUPLICA) (PODE COLOCAR VARIOS RELACIONAMENTOS)
MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
MERGE (P)-[R : PERTENCE]->(C)
RETURN P,C,R

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'BRASIL' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S
--
MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ARGENTINA' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'URUGUAI' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ITALIA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ESPANHA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'FRANCA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ALEMANHA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'INGLATERRA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'EUA' AND C.NOME='AMERICA DO NORTE'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'CANADA' AND C.NOME='AMERICA DO NORTE'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'JAPAO' AND C.NOME='ASIA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'NIGERIA' AND C.NOME='AFRICA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S