---------------
-- Neo4j
---------------
:HELP
:SEVER DISCONNECT
:SERVER CONNECT 
:PLAY START
:SERVER STATUS
:SYSINFO
:QUERIES




principais palabras da linguagem CYPHER

CREATE = CRIAR - NODE E RELACIONAMENTO
MATCH = SELECT
RETURN = MOSTRA O VALOR CRIADO (RETORNA)
WHERE = SELECAO
SET = UPDATE
REMOVE = DELETE
MERGE = CRIAR UM OBJETO DERIVADO

LABEL - ANALOGA AO NOME DE UMA TABELA 

PROPRIEDADE - ANALOGA AO NOME DE COLUNAS

---INTRODUZINDO O WHERE
MATCH (n) WHERE id(n)=3 RETURN (n)
MATCH (n) WHERE id(n)=8 RETURN (n)

-SO TEM TIME 
MATCH (n:TIME) RETURN (n)
-SO DE FUTEBOL
MATCH (n:TIME:FUTEBOL) RETURN (n)
- TRAZENDO TIME ESPECIFICO
MATCH (n) WHERE n.NOME='FLAMENGO' RETURN (n)
- TRAZENDO MAIS DE UM 
MATCH (n),(y) WHERE n.NOME='FLAMENGO' AND y.NOME='FLUMINENSE' RETURN n,y
===========================

CREATE (:SELECAO  {NOME: 'BRASIL',COR:'VERDE',COR:'AMARELO'})
CREATE (:SELECAO  {NOME: 'ARGENTINA',COR:'AZUL',COR:'BRANCO'})
CREATE (:SELECAO  {NOME: 'URUGUAI',COR:'AZUL',COR:'BRANCO'})

CREATE (:SELECAO  {NOME: 'FRANCA',COR:'AZUL',COR:'BRANCO', COR:'VERMELHO'})
CREATE (:SELECAO  {NOME: 'ESPANHA',COR:'VERMELHO',COR:'AMARELO'})
CREATE (:SELECAO  {NOME: 'ALEMANHA',COR:'VERMELHO',COR:'AMARELO', COR:'PRETO'})
CREATE (:SELECAO  {NOME: 'INGLATERRA',COR:'VERMELHO',COR:'BRANCO'})
CREATE (:SELECAO  {NOME: 'ITALIA',COR:'VERDE',COR:'VERMELHO',COR:'BRANCO'})

CREATE (:SELECAO  {NOME: 'EUA',COR:'AZUL',COR:'VERMELHO', COR:'BRANCO'})
CREATE (:SELECAO  {NOME: 'JAPAO',COR:'BRANCO',COR:'VERMELHO'})
CREATE (:SELECAO  {NOME: 'NIGERIA',COR:'VERDE',COR:'BRANCO'})

CREATE (:SELECAO  {NOME: 'CANADA',COR:'BRANCO',COR:'VERMELHO'})
CREATE (:SELECAO  {NOME: 'COLOMBIA',COR:'AMARELO',COR:'VERMELHO', COR:'AZUL'})

---------------------------------------------

CREATE (:SELECAO  {NOME: 'BRASIL',COR:'VERDE,AMARELO'})
CREATE (:SELECAO  {NOME: 'ARGENTINA',COR:'AZUL,BRANCO'})
CREATE (:SELECAO  {NOME: 'URUGUAI',COR:'AZUL,BRANCO'})

CREATE (:SELECAO  {NOME: 'FRANCA',COR:'AZUL,BRANCO,VERMELHO'})
CREATE (:SELECAO  {NOME: 'ESPANHA',COR:'VERMELHO,AMARELO'})
CREATE (:SELECAO  {NOME: 'ALEMANHA',COR:'VERMELHO,AMARELO,PRETO'})
CREATE (:SELECAO  {NOME: 'INGLATERRA',COR:'VERMELHO,BRANCO'})
CREATE (:SELECAO  {NOME: 'ITALIA',COR:'VERDE,VERMELHO,BRANCO'})

CREATE (:SELECAO  {NOME: 'EUA',COR:'AZUL,VERMELHO,BRANCO'})
CREATE (:SELECAO  {NOME: 'JAPAO',COR:'BRANCO,VERMELHO'})
CREATE (:SELECAO  {NOME: 'NIGERIA',COR:'VERDE,BRANCO'})

CREATE (:SELECAO  {NOME: 'CANADA',COR:'BRANCO,VERMELHO'})
CREATE (:SELECAO  {NOME: 'COLOMBIA',COR:'AMARELO,VERMELHO,AZUL'})

------------------------------------------------

MATCH (n) WHERE n.COR CONTAINS "VERMELHO" AND n.COR CONTAINS "BRANCO" RETURN (n)

MATCH (n) WHERE n.COR CONTAINS "VERDE" OR n.COR CONTAINS "ROSA" RETURN (n)

------------------------------------------------


--CRIANDO CONTINENTES

CREATE (:CONTINENTE {NOME: 'AMERICA DO SUL'})
CREATE (:CONTINENTE {NOME: 'AMERICA DO NORTE'})
CREATE (:CONTINENTE {NOME: 'EUROPA'})
CREATE (:CONTINENTE {NOME: 'AFRICA'})
CREATE (:CONTINENTE {NOME: 'ASIA'})


----------------------------------------------
--CRIANDO RELACIONAMENTO 

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
CREATE (P)-[R : PERTENCE]->(C)
RETURN P,C,R

--RELACIONAMENTO BIDIMENCIONAL

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
CREATE (P)<-[R : CONTEM]-(C)
RETURN P,C,R]

--TRAZENDO O RELACIONAMENTO 

MATCH (P: SELECAO), (C: CONTINENTE)
WHERE P.NOME = 'COLOMBIA'AND C.NOME = 'AMERICA DO SUL'
RETURN P,C

--OUTRA FORMA 

MATCH (P: SELECAO)-[R:PERTENCE]->(C: CONTINENTE)
WHERE P.NOME = 'COLOMBIA'AND C.NOME = 'AMERICA DO SUL'
RETURN P,C,R

--DELETANDO RELACIONAMENTO
MATCH (P:SELECAO)-[R:PERTENCE]->(C:CONTINENTE)
WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
DELETE R
RETURN P,C

--MERGE (nÃO DUPLICA) (PODE COLOCAR VARIOS RELACIONAMENTOS)
MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'COLOMBIA' AND C.NOME='AMERICA DO SUL'
MERGE (P)-[R : PERTENCE]->(C)
RETURN P,C,R

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'BRASIL' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S
--
MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ARGENTINA' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'URUGUAI' AND C.NOME='AMERICA DO SUL'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ITALIA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ESPANHA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'FRANCA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'ALEMANHA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'INGLATERRA' AND C.NOME='EUROPA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'EUA' AND C.NOME='AMERICA DO NORTE'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'CANADA' AND C.NOME='AMERICA DO NORTE'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'JAPAO' AND C.NOME='ASIA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S

MATCH (P :SELECAO), (C :CONTINENTE) WHERE P.NOME = 'NIGERIA' AND C.NOME='AFRICA'
MERGE (P)<-[R : CONTEM]-(C)
MERGE (P)-[S : PERTENCE]->(C)
RETURN P,C,R,S