/* Documento JSON */
[
	{ 
	  "aeroPartida": "SDU",
	  "aeroChegada": "YYZ",
	  "aviao": "Airbus A380",
	  "distacia":30000,
	  "intercontinental": true
	}
]

/* Exemplo Aeroporto SQL*/
create database aviacao;

/* verificar as bases de dados */
show databases;

/*conectar*/
use aviacao;

/*mostrar tabelas*/
show tables;

/*criar tabelas*/
create table aviao(
	IDAVIAO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(100)
);
CREATE TABLE AEROPORTO(
	IDAEROPORTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SIGLA CHAR(2)
);
CREATE TABLE VOOS(
	IDVIAGEM INT PRIMARY KEY AUTO_INCREMENT,
	ID_AVIAO INT,
	ID_PARTIDA INT,
	ID_CHEGADA INT,
	DISTANCIA INT,
	INTERCONTINENTAL BINARY
);

ALTER TABLE VOOS ADD CONSTRAINT FK_AVIAO
FOREIGN KEY (ID_AVIAO) REFERENCES AVIAO(IDAVIAO);

ALTER TABLE VOOS ADD CONSTRAINT FK_AERO_PARTIDA
FOREIGN KEY (ID_PARTIDA) REFERENCES AEROPORTO(IDAEROPORTO);

ALTER TABLE VOOS ADD CONSTRAINT FK_AERO_CHEGADA
FOREIGN KEY (ID_CHEGADA) REFERENCES AEROPORTO(IDAEROPORTO);

/* VERIFICANDO AS TABELAS */
DESC 'NOME DA TABELA'

/* VERIFICANDO OS REGISTROS DAS TABELAS */
SELECT * FROM AVIAO;
SELECT * FROM AEROPORTO;
SELECT * FROM VOOS;
limit one

/* ALTERANDO TABELAS */
ALTER TABLE AEROPORTO
MODIFY COLUMN SIGLA CHAR(3);
DESC 'NOME DA TABELA'