/* RELACIONAL 
-- 1 - CRIAR BANCO
-- 2 - CONECTOU
-- 3 - CRIOU TABELAS
	   -- AVIAO
	   -- AEROPORTOS
	   -- VOOS
-- 4 - ENTROU COM OS DADOS
	   -- AVIAO
	   -- AEROPORTOS
	   -- VOOS
-- 5 - CONSULTAR OS DADOS*/

/* NOSQL */
-- ARMAZENA DADOS NO FORMATO JSON --
[
	(
	  AEROPARTIDA: "SDU",
	  AEROCHEGADA: "YYZ",
	  AVIAO: "AIRBUS A380",
	  DISTANCIA: 30000,
	  INTERCONTINENTAL: TRUE
	),
	(
	  AEROPARTIDA: "GRU",
	  AEROCHEGADA: "GIG",
	  AVIAO: "AIRBUS A320",
	  DISTANCIA: 550,
	  INTERCONTINENTAL: FALSE
	)
]