---------- 
-- FILTROS
----------

create table clientes(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1)
);

INSERT INTO CLIENTES VALUES(NULL,'JOAO','M');
INSERT INTO CLIENTES VALUES(NULL,'JORGE','M');
INSERT INTO CLIENTES VALUES(NULL,'CLARA','F');
INSERT INTO CLIENTES VALUES(NULL,'LILIAN','F');

DELETE FROM CLIENTES;

SELECT * FROM CLIENTES;

DELETE FROM CLIENTES WHERE IDCLIENTE = 5;
DELETE FROM CLIENTES WHERE SEXO = 'F';

-- FILTRANDO NO MONGODB